version: 2
updates:
  - package-ecosystem: pip
    directory: /
    groups:
      minor-and-patch:
        update-types:
          - patch
          - minor
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
