name: Sync metadata with Datenraum

on:
  push:
    branches: ["main"]

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  sync_demo_datenraum:
    uses: serlo/metadata-exports/.github/workflows/sync-datenraum-job.yml
    with:
      target_environment: demo
      client_id: ${{ secrets.CLIENT_ID_DEMO }}
      client_secret: ${{ secrets.CLIENT_SECRET_DEMO }}

  sync_postdam_datenraum:
    needs: sync_demo_datenraum
    uses: serlo/metadata-exports/.github/workflows/sync-datenraum-job.yml
    with:
      target_environment: postdam
      client_id: ${{ secrets.CLIENT_ID_POSTDAM }}
      client_secret: ${{ secrets.CLIENT_SECRET_POSTDAM }}
