name: Sync metadata with Datenraum

on:
  push:
    branches: ["main"]

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  sync_demo_datenraum:
    uses: ./.github/workflows/sync-datenraum-job.yml
    with:
      target_environment: demo
  sync_postdam_datenraum:
    # Let's not overload the api running then at same time
    needs: sync_demo_datenraum
    uses: ./.github/workflows/sync-datenraum-job.yml
    with:
      target_environment: postdam
