name: Publish metadata

on:
  push:
    branches: ["main"]

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install python requirements
        run: pipenv install

      - name: Download metadata from Serlo Metadata API
        run: pipenv run python download_metadata.py public/serlo-metadata.json

      - name: Download metadata from Datenraum (DEMO)
        run: pipenv run python download_datenraum_nodes.py public/serlo-datenraum-demo.json
        env:
          BASE_URL: https://dam.demo.meinbildungsraum.de/datenraum
          CLIENT_ID: ${{ secrets.CLIENT_ID_DEMO }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_DEMO }}

      - name: Download metadata from Datenraum (DEV)
        run: pipenv run python download_datenraum_nodes.py public/serlo-datenraum-dev.json
        env:
          BASE_URL: https://dam-dev.nbpdev.de/datenraum
          CLIENT_ID: ${{ secrets.CLIENT_ID_DEV }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_DEV }}

      - name: Generate RSS export for SODIX Mundo
        run: pipenv run python convert2rss.py public/serlo-metadata.json public/serlo-metadata.rss

      - name: Sync metadata from Serlo Metadata API to Datenraum
        run: pipenv run python update_datenraum_nodes.py public/serlo-metadata.json public/serlo-datenraum-demo.json
        env:
          BASE_URL: https://dam.demo.meinbildungsraum.de/datenraum
          CLIENT_ID: ${{ secrets.CLIENT_ID_DEMO }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_DEMO }}

      - name: Sync metadata from Serlo Metadata API to Datenraum
        run: pipenv run python update_datenraum_nodes.py public/serlo-metadata.json public/serlo-datenraum-dev.json
        env:
          BASE_URL: https://dam-dev.nbpdev.de/datenraum
          CLIENT_ID: ${{ secrets.CLIENT_ID_DEV }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_DEV }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
