name: Publish metadata

on:
  push:
    branches: ['main']

  workflow_dispatch:

  schedule:
    - cron: '0 6 * * THU'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Prepare public folder
        id: folder
        run: |
          echo "name=public" >> $GITHUB_OUTPUT

      - name: Install dev requirements
        run: pipenv install

      - run: pipenv run python download_metadata.py public/serlo-metadata.json

      - run: pipenv run python convert2rss.py public/serlo-metadata.json public/serlo-metadata.rss

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ steps.folder.outputs.name }}

  deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
