name: Sync to GitLab
on:
  push:
    branches:
      - staging
      - production

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to GitLab
        uses: kulla/sync-to-gitlab@v1
        with:
          owner: stephan_kulla
          repository_name: serlo-cloudflare-worker
          token: ${{ secrets.GITLAB_TOKEN }}
