name: Sync Datenraum

on:
  workflow_call:
    inputs:
      target_environment:
        required: true
        type: string
      client_id:
        required: true
        type: string
      client_secret:
        required: true
        type: string

jobs:
  sync_metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install python requirements
        run: pipenv install

      - name: Set credentials for corresponding Datenraum
        run: |
          echo "DATENRAUM_ENVIRONMENT=${{ inputs.target_environment }}" >> "$GITHUB_ENV"
          echo "CLIENT_ID=${{ inputs.client_id }}" >> "$GITHUB_ENV"
          echo "CLIENT_SECRET=${{ inputs.client_secret }}" >> "$GITHUB_ENV"

      - name: Download metadata from Serlo Metadata API
        run: pipenv run python download_metadata.py public/serlo-metadata.json

      - name: Validate nodes according to AMB Schema
        run: pipenv run python validate_nodes.py

      - name: Download metadata from Datenraum
        run: pipenv run python download_datenraum_nodes.py public/serlo-datenraum.json

      - name: Sync metadata from Serlo Metadata API to the ${{ inputs.target_environment }} Datenraum environment
        run: pipenv run python update_datenraum_nodes.py public/serlo-metadata.json public/serlo-datenraum.json
